### Supplemental Table 1: Table of identified taxa with associated functional traits and references

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r}
###############################
# LOAD LIBRARIES
###############################
library(tidyverse)
library(here)
library(kableExtra)


###############################
# READ IN DATA
###############################
species_lit <- read_csv(here("Data", "Species_FE_Literature.csv"))
abund <- read_csv(here("Data", "Species_Abundances_wide.csv"))


###############################
# PROCESS FOR TABLE
###############################
inTaxa <- abund %>% 
  pivot_longer(cols = 2:ncol(abund), names_to = "Taxa", values_to = "Values") %>% 
  distinct(Taxa)

#### Modify Lit categories for special character strings
species_lit <- species_lit %>%
  mutate(Lit_Energetic_Resource = if_else(grepl("Acuna and Zamponi 1995", Lit_Energetic_Resource),
                                          as.character("Acuña and Zamponi 1995"),
                                          Lit_Energetic_Resource))


species <- species_lit %>% 
  right_join(inTaxa) %>%  # make sure we only have species from Varari
  mutate(Taxa = if_else(Taxa == "Cyanobacteria", "Cyanobacteria unknown", Taxa)) %>% 
  rename(`Functional Entity` = FE)

#### Unite columns with literature citations
#### Use full phrasing for FE's
species <- species %>% 
  unite(Lit_Identification:Lit_Energetic_Resource, col = "Source", sep = ", ", na.rm = TRUE, remove = TRUE) %>% 
  mutate(Morphology = if_else(Morphology == "Br", "Branching",
                      if_else(Morphology == "Fol", "Foliose", 
                      if_else(Morphology == "Stol", "Stolonial",
                      if_else(Morphology == "Enc", "Encrusting",
                      if_else(Morphology == "Mush", "Mushroom",
                      if_else(Morphology == "Poly", "Polypoid",
                      if_else(Morphology == "Mas", "Massive", 
                      if_else(Morphology == "Dig", "Digitate",
                      if_else(Morphology == "Fil", "Filamentous",
                      if_else(Morphology == "Sph", "Spherical", Morphology)))))))))),
         Calcification = if_else(Calcification == "AC", "Articulated",
                         if_else(Calcification == "Non-AC", "Non-articulated",
                         if_else(Calcification == "Herm", "Hermatypic", 
                         if_else(Calcification == "NC", "Non-calcifying", Calcification)))),
         Energetic_Resource = if_else(Energetic_Resource == "Auto", "Autotroph",
                              if_else(Energetic_Resource == "Het", "Heterotroph",
                              if_else(Energetic_Resource == "Mix", "Mixotroph", Energetic_Resource))),
         Source = if_else(is.na(Source), " ", Source)) %>% 
  rename(`Trophic Group` = Energetic_Resource) %>% 
  select(-Identification_notes)

# split into two tables for separate pages
sp1 <- species[1:24,]
sp2 <- species[25:nrow(species),]

speciesTable1 <- sp1 %>% 
  kbl() %>% 
  kable_classic(html_font = "Times New Roman",
                font_size = 20) %>% 
  row_spec(0, italic = TRUE, bold = TRUE) %>%  # header row
  column_spec(1, italic = TRUE) %>% 
  column_spec(1:7, background = "white")

speciesTable2 <- sp2 %>% 
  kbl() %>% 
  kable_classic(html_font = "Times New Roman",
                font_size = 20) %>% 
  row_spec(0, italic = TRUE, bold = TRUE) %>%  # header row
  column_spec(1, italic = TRUE) %>% 
  column_spec(1:7, background = "white")

```
```{r, eval = FALSE}
speciesTable1 %>%
  as_image(file = here("Output", "SpeciesTable1.png"))
speciesTable2 %>%
  as_image(file = here("Output", "SpeciesTable2.png"))
```
